package com.medicationtracker.app.util

object Constants {
    const val ACTION_SET_EXACT_ALARM = "ACTION_SET_EXACT_ALARM"
    const val ACTION_SET_REPETITIVE_WEEKLY_ALARM = "ACTION_SET_REPETITIVE_WEEKLY_ALARM"
    const val ACTION_SET_REPETITIVE_DAILY_ALARM = "ACTION_SET_REPETITIVE_DAILY_ALARM"

    const val EXTRA_EXACT_ALARM_TIME = "EXTRA_EXACT_ALARM_TIME"
}
